# Generated by Django 5.2.9 on 2025-12-09 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_videotask_result_url_videotask_result_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_prompt', models.TextField(help_text='用户输入的原始想法')),
                ('style', models.CharField(default='Cinematic', max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('optimized_prompt', models.TextField(help_text='AI优化后的提示词')),
                ('credits_used', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt History',
                'verbose_name_plural': 'Prompt Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
