# Generated by Django 5.2 on 2025-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_prompthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompthistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="videotask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
