# Generated by Django 5.2 on 2026-01-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0005_prompttask"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompttask",
            name="model",
            field=models.CharField(default="sora", max_length=50),
        ),
        migrations.AddField(
            model_name="videotask",
            name="generation_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videotask",
            name="model",
            field=models.CharField(default="sora", max_length=50),
        ),
    ]
