# Generated by Django 5.2 on 2026-01-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0006_prompttask_model_videotask_generation_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompthistory",
            name="credits_used",
            field=models.IntegerField(default=20),
        ),
    ]
