# Generated by Django 5.2 on 2025-12-29 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now, unique=True),
                ),
                ("api_call_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Daily Statistic",
                "verbose_name_plural": "Daily Statistics",
                "ordering": ["-date"],
            },
        ),
    ]
