# Generated by Django 5.2 on 2025-12-29 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SoraApp", "0002_userapiusage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystats",
            name="prompt_gen_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="video_gen_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="visit_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userapiusage",
            name="prompt_gen",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userapiusage",
            name="video_gen",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UserVisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
