# Generated by Django 5.2 on 2025-12-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SoraApp", "0004_apirequestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisitlog",
            name="path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
