# Generated by Django 5.2 on 2026-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SoraApp", "0005_uservisitlog_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="配置键"),
                ),
                ("value", models.TextField(verbose_name="配置值")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="描述"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "系统设置",
                "verbose_name_plural": "系统设置",
            },
        ),
    ]
