# Generated by Django 5.2 on 2025-12-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="balance_after",
            field=models.IntegerField(
                help_text="User balance after transaction", null=True
            ),
        ),
    ]
