# Generated by Django 5.2 on 2025-12-27 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_credittransaction_balance_after"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invitation_code",
            field=models.CharField(
                blank=True,
                help_text="Unique invitation code for the user",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who invited this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="User's verified phone number",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
    ]
