# Generated by Django 5.2 on 2025-12-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_invitation_code_user_invited_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last SMS password verification",
                null=True,
            ),
        ),
    ]
