# Generated by Django 5.2 on 2025-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_password_verified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credittransaction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
